spring:
  datasource:
    driverClassName: 'org.sqlite.JDBC'
    url: 'jdbc:sqlite:S:\weatherapp\media\weewx.sdb?cache=shared'
  jpa:
    properties:
      hibernate:
        dialect: com.github.marcel1504.weatherapp.producer.config.sql.SQLiteDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

weatherapp:
  cronjob:
    weatherDataUpdate: '0 0 3 * * *'
    weatherDataSync: '0 0/1 * * * *'
    weatherCamUpload: '0 0 3 * * *'
  inputFilePath:
    weatherCam: 'S:\weatherapp\media\current.jpg'
  consumerServices:
    - url: 'https://localhost/w/consumer'
      username: 'test1'
      password: 'test1'
  multiplier: # factors to convert the database values to the required format
    rain: 10 # liters per square meters
    wind: 1 # kmh