server:
  port: 8092

spring:
  datasource:
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://homenet:3306/wetterarnsdorf?serverTimezone=CET&useSSL=false'
    username: 'wetterarnsdorf'
    password: 'RMHUYxf@RqRT4qqj7+rMxW?N'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
  jackson:
    time-zone: 'CET'

weatherdataproducer:
  cronjob:
    weatherDataUpdate: '0 0/10 * * * *'
    weatherDataSync: '0 0 3 * * *'
    weatherCamUpload: '0 0/15 * * * *'
  inputFilePath:
    weatherData: 'I:\Projekte\wetterarnsdorf\config\media\weather.json'
    weatherCam: 'I:\Projekte\wetterarnsdorf\config\media\current.jpg'
  consumerService:
    url: 'http://hausnetz:8091'
    username: 'consumerusertest'
    password: 'consumerusertest'
  calculation:
    rain:
      hitCounterMax: 4096
      amountPerHit: 295
      acceptAsRainThresholdHits: 3