spring:
  datasource:
    driverClassName: 'org.sqlite.JDBC'
    url: 'jdbc:sqlite:S:/weatherapp/media/weewx.sdb'
  jpa:
    properties:
      hibernate:
        dialect: com.github.marcel1504.weatherapp.producer.config.sql.SQLiteDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

weatherapp:
  cronjob:
    weatherDataUpdate: '0 0/1 * * * *'
  consumerServices:
    - url: 'http://localhost:8082'
      username: 'ber1'
      password: 'test'
  multiplier: # factors to convert the database values to the required format
    rain: 10 # liters per square meters
    wind: 1 # kmh