server:
  port: 8092

spring:
  datasource:
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://hausnetz:3306/wetterarnsdorf?serverTimezone=CET&useSSL=false'
    username: 'backend'
    password: 'SEbvTMT@j5vW'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
  jackson:
    time-zone: 'CET'

weatherdataproducer:
  cronjob:
    weatherDataUpdate: '0 0/1 * * * *'
    weatherCamUpload: '0 0/15 * * * *'
  inputFilePath:
    weatherData: 'I:\Projekte\wetterarnsdorf\config\media\weather.json'
    weatherCam: 'I:'
  consumerServiceUrl: 'http://homenet:8091'
  calculation:
    rain:
      hitCounterMax: 4096
      amountPerHit: 295
      acceptAsRainThresholdHits: 3