server:
  port: 8092

spring:
  datasource:
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://wetterstation:3306/weatherstation?serverTimezone=CET&useSSL=false'
    username: 'wetterstation'
    password: 'yMpbGVU79iYSAfBJNc0b'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

weatherdataproducer:
  locationKey: 'ARNSDORFOBERDORF'
  cronjob:
    weatherDataUpdate: '0 0 3 * * *'
    weatherDataSync: '0 0/1 * * * *'
    weatherCamUpload: '0 0 3 * * *'
  inputFilePath:
    weatherCam: 'I:\Projekte\wetterarnsdorf\config\media\current.jpg'
  consumerService:
    url: 'http://localhost:8091'
    username: 'test'
    password: 'test'
  multiplier: # factors to convert the database values to the required format
    rain: 10 # liters per square meters
    wind: 1 # kmh