version: '3.5'

services:
  portainer:
    image: portainer/portainer-ce:latest
    hostname: portainer
    restart: always
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
  http-proxy-server:
    image: nginx:alpine
    restart: always
    depends_on:
      - portainer
      - weewx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    expose:
      - "80"
    ports:
      - "80:80"
  weewx:
    image: felddy/weewx:latest
    hostname: weewx
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - TIMEZONE=Europe/Berlin
    devices:
      - /dev/bus/usb:/dev/bus/usb
  producer:
    image: marcel1504/weatherapp-producer:latest
    restart: always
    hostname: producer
    expose:
      - '8080'
    environment:
      - TZ=Europe/Berlin
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/data/weewx.sdb?cache=shared
      - WEATHERAPP_INPUTFILEPATH_WEATHERCAM=/data/current.jpg
      - WEATHERAPP_CONSUMERSERVICES_0_URL=${CONSUMER_URL}
      - WEATHERAPP_CONSUMERSERVICES_0_USERNAME=${CONSUMER_USERNAME}
      - WEATHERAPP_CONSUMERSERVICES_0_PASSWORD=${CONSUMER_PASSWORD}
    volumes:
      - type: bind
        source: ./data/weewx.sdb
        target: /data/weewx.sdb
      - type: bind
        source: ./data/current.jpg
        target: /data/current.jpg
volumes:
  portainer:
