name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: gradle test --debug
      - name: BootJar Build
        run: gradle bootJar
      - uses: actions/upload-artifact@v2
        with:
          name: wetterarnsdorf-weatherdataproducer
          path: build/libs
